apiVersion: v1
kind: Pod
metadata:
 name: cm
 labels:
   htcondor-role: cm
spec:
 restartPolicy: Never
 containers:
  - name: cm
    image: htcondor/cm:8.9.11-el7
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1"
        memory: "10G"
        ephemeral-storage: "10G"
      requests:
        cpu: "1"
        memory: "10G"
        ephemeral-storage: "10G"
    volumeMounts:
      - name: htcondor-pool-password
        mountPath: /root/secrets
        readOnly: true
 volumes:
  - name: htcondor-pool-password
    secret:
      secretName: htcondor-pool-password
      items:
      - key: htcondor-pool-password
        path: pool_password